services:
  - name: my-app
    env:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - backend/**
    build:
      image: dev-center-backend:latest
      dockerfile: Dockerfile
    http:
      port: 5000
