openapi: 3.0.3
info:
  title: Dev Center
  description: API documentation for Dev Center
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/users/register:
    post:
      tags:
        - Users & Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: User registration successful
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/users/login:
    post:
      tags:
        - Users & Auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
              required:
                - email
                - password
      responses:
        '200':
          description: User login successful
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /api/auth:
    get:
      tags:
        - Users & Auth
      summary: Get an authentication token
      parameters:
        - name: x-auth-token
          in: header
          description: Authentication token obtained after login
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Authentication token retrieval successful
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /profiles/user/{id}:
    get:
      tags:
        - "Profiles"
      summary: "Get user profile"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user profile to return"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"

  /api/profiles/experience:
    put:
      tags:
        - "Profiles"
      summary: "Add experience"
      parameters:
        - in: "body"
          name: "body"
          description: "Experience object that needs to be added"
          required: true
          schema:
            type: "object"
            properties:
              title:
                type: "string"
              company:
                type: "string"
              location:
                type: "string"
              from:
                type: "string"
              to:
                type: "string"
              current:
                type: "boolean"
              description:
                type: "string"
      responses:
        200:
          description: "successful operation"

    delete:
      tags:
        - "Profiles"
      summary: "Delete experience"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of experience to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"

  /api/profiles/education:
    put:
      tags:
        - "Profiles"
      summary: "Add education"
      parameters:
        - in: "body"
          name: "body"
          description: "Education object that needs to be added"
          required: true
          schema:
            type: "object"
            properties:
              school:
                type: "string"
              degree:
                type: "string"
              fieldofstudy:
                type: "string"
              from:
                type: "string"
              to:
                type: "string"
              current:
                type: "boolean"
              description:
                type: "string"
      responses:
        200:
          description: "successful operation"
  /api/profiles:
    get:
      tags:
        - "Profiles"
      description: Returns a list of all profiles
      produces:
        - application/json
      parameters:
        - name: x-auth-token
          in: header
          description: The authentication token
          required: true
          type: string
      responses:
        200:
          description: A list of profiles
    post:
      tags:
        - "Profiles"
      description: Adds a new profile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-auth-token
          in: header
          description: The authentication token
          required: true
          type: string
        - in: body
          name: body
          description: The profile to add
          required: true
          schema:
            type: object
            properties:
              company:
                type: string
              website:
                type: string
              location:
                type: string
              bio:
                type: string
              status:
                type: string
              githubusername:
                type: string
              skills:
                type: string
              youtube:
                type: string
              twitter:
                type: string
              instagram:
                type: string
              linkedin:
                type: string
              facebook:
                type: string
      responses:
        201:
          description: The newly created profile
  /api/profiles/education/{id}:
    delete:
      tags:
        - "Profiles"
      description: Deletes a profile's education entry
      produces:
        - application/json
      parameters:
        - name: x-auth-token
          in: header
          description: The authentication token
          required: true
          type: string
        - name: id
          in: path
          description: The ID of the education entry to delete
          required: true
          type: string
      responses:
        204:
          description: The education entry was deleted successfully
    